root = "."
tmp_dir = "tmp"

[build]
  cmd        = "go build -o ./tmp/main ."
  bin        = "./tmp/main"
  full_bin   = "./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "uploads", "db", "deployment", "test"]
  delay      = 500
  kill_delay = "500ms"
  rerun_delay = 500

[log]
  time = true

[color]
  build = "yellow"
  runner = "green"
  watcher = "cyan"
  main = "magenta"

[misc]
  clean_on_exit = true
