services:
  api:
    image: ghcr.io/ahmdriffai/diengsid-backend:${API_TAG}
    container_name: diengsid-api
    restart: always
    command: sh -c "apk add --no-cache tzdata && ./main"
    ports:
      - 9000:9000
    volumes:
      - ./config:/app/config
    networks:
      - diengsid-net
    depends_on:
      - database

  client:
    image: ghcr.io/ahmdriffai/diengsid-client:${CLIENT_TAG}
    container_name: diengsid-client
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - API_URL=http://api:9000
    networks:
      - diengsid-net
    depends_on:
      - api

  cloudflared-api:
    image: cloudflare/cloudflared:latest
    container_name: diengsid-cloudflared-api
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_API_TOKEN}
    networks:
      - diengsid-net

  cloudflared-client:
    image: cloudflare/cloudflared:latest
    container_name: diengsid-cloudflared-client
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_CLIENT_TOKEN}
    networks:
      - diengsid-net

  # database:
  #   image: postgres:15-alpine
  #   container_name: diengsid-database
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: db_diengsid
  #     TZ: Asia/Jakarta
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - database_data:/var/lib/postgresql/data
  #   networks:
  #     - diengsid-net

networks:
  diengsid-net:
    name: diengsid-net
    driver: bridge

# volumes:
#   database_data:
#     name: database-data
