app:
  env: development
  name: "Diengs ID API"
  prefork: false
  url: http://localhost:9000
  cors_origins: http://localhost:3000
  cookie_secure: false
  cookie_domain:

web:
  port: 9000

log:
  level: 8

database:
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  name: "db_diengsid"
  sslmode: "disable"
  timezone: "Asia/Jakarta"
  pool:
    idle: 10
    max: 100
    lifetime: 300

mail:
  host: smtp.gmail.com
  port: 587
  username: iddiengs@gmail.com
  password: "lkpe qqmx degv biip"

googe:
  clientId: 314501383101-t83bulhqb5ugib4s57t5hepheqt2rdgo.apps.googleusercontent.com

doku:
  client_id: "BRN-0222-1773906551013"
  secret_key: "SK-uTjSNjeQAzchNhy54WyP"
  is_sandbox: true
  success_url: "http://localhost:3000/payment/result?status=success"
  failed_url: "http://localhost:3000/payment/result?status=failed"
  notification_url: "https://e543-182-8-211-227.ngrok-free.app/api/payment/notify"
