app:
  name: "Diengs ID API"
  prefork: false

web:
  port: 9000

log:
  level: 8

database:
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  name: "db_diengsid"
  sslmode: "disable"
  timezone: "Asia/Jakarta"
  pool:
    idle: 10
    max: 100
    lifetime: 300

mail:
  host: smtp.gmail.com
  port: 587
  username:
  password:

fonnte:
  token:

googe:
  clientId:
